version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  pocketbase:
    image: elestio/pocketbase:latest
    restart: always
    user: 0:0
    ports:
      - "8090:8090"
    volumes:
      - ./data:/pb_data
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
